/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        "Popions-Black": ["Popions-Black", "sans-serif"],
        "Popions-BlackItalic": ["Popions-BlackItalic", "sans-serif"],
        "Popions-Bold": ["Popions-Bold", "sans-serif"],
        "Popions-BoldItalic": ["Popions-BoldItalic", "sans-serif"],
        "Popions-ExtraBold": ["Popions-ExtraBold", "sans-serif"],
        "Popions-ExtraBoldItalic": ["Popions-ExtraBoldItalic", "sans-serif"],
        "Popions-ExtraLight": ["Popions-ExtraLight", "sans-serif"],
        "Popions-ExtraLightItalic": ["Popions-ExtraLightItalic", "sans-serif"],
        "Popions-Italic": ["Popions-Italic", "sans-serif"],
        "Popions-LightItalic": ["Popions-LightItalic", "sans-serif"],
        "Popions-Light": ["Popions-Light", "sans-serif"],
        "Popions-Medium": ["Popions-Medium", "sans-serif"],
        "Popions-MediumItalic": ["Popions-MediumItalic", "sans-serif"],
        "Popions-Regular": ["Popions-Regular", "sans-serif"],
        "Popions-SemiBold": ["Popions-SemiBold", "sans-serif"],
        "Popions-SemiBoldItalic": ["Popions-SemiBoldItalic", "sans-serif"],
        "Popions-Thin": ["Popions-Thin", "sans-serif"],
        "Popions-ThinItalic": ["Popions-ThinItalic", "sans-serif"],
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          50: "var(--primary-50)",
          100: "var(--primary-100)",
          200: "var(--primary-200)",
          300: "var(--primary-300)",
          400: "var(--primary-400)",
          500: "var(--primary-500)",
          600: "var(--primary-600)",
          700: "var(--primary-700)",
          800: "var(--primary-800)",
          900: "var(--primary-800)",
          950: "var(--primary-950)",
        },
        secondary: {
          50: "var(--secondary-50)",
          100: "var(--secondary-100)",
          200: "var(--secondary-200)",
          300: "var(--secondary-300)",
          400: "var(--secondary-400)",
          500: "var(--secondary-500)",
          600: "var(--secondary-600)",
          700: "var(--secondary-700)",
          800: "var(--secondary-800)",
          900: "var(--secondary-800)",
          950: "var(--secondary-950)",
        },
        success: {
          50: "var(--success-50)",
          100: "var(--success-100)",
          200: "var(--success-200)",
          300: "var(--success-300)",
          400: "var(--success-400)",
          500: "var(--success-500)",
          600: "var(--success-600)",
          700: "var(--success-700)",
          800: "var(--success-800)",
          900: "var(--success-800)",
          950: "var(--success-950)",
        },
        warning: {
          50: "var(--warning-50)",
          100: "var(--warning-100)",
          200: "var(--warning-200)",
          300: "var(--warning-300)",
          400: "var(--warning-400)",
          500: "var(--warning-500)",
          600: "var(--warning-600)",
          700: "var(--warning-700)",
          800: "var(--warning-800)",
          900: "var(--warning-800)",
          950: "var(--warning-950)",
        },
        error: {
          50: "var(--error-50)",
          100: "var(--error-100)",
          200: "var(--error-200)",
          300: "var(--error-300)",
          400: "var(--error-400)",
          500: "var(--error-500)",
          600: "var(--error-600)",
          700: "var(--error-700)",
          800: "var(--error-800)",
          900: "var(--error-800)",
          950: "var(--error-950)",
        },
        info: {
          50: "var(--info-50)",
          100: "var(--info-100)",
          200: "var(--info-200)",
          300: "var(--info-300)",
          400: "var(--info-400)",
          500: "var(--info-500)",
          600: "var(--info-600)",
          700: "var(--info-700)",
          800: "var(--info-800)",
          900: "var(--info-800)",
          950: "var(--info-950)",
        },
        gray: {
          50: "var(--gray-50)",
          100: "var(--gray-100)",
          200: "var(--gray-200)",
          300: "var(--gray-300)",
          400: "var(--gray-400)",
          500: "var(--gray-500)",
          600: "var(--gray-600)",
          700: "var(--gray-700)",
          800: "var(--gray-800)",
          900: "var(--gray-800)",
          950: "var(--gray-950)",
        },
      },
      width: {
        bottomNaivigationBar: "98%",
      },
    },
  },
  plugins: [],
};
